<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBaAqPZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBaAqPZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBaAqPZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBaAqPZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXBaAqPZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XBaAqPZ',
    'container.build_id' => 'f02cfb40',
    'container.build_time' => 1566399356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBaAqPZ');
