<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlG2YlC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlG2YlC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXlG2YlC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXlG2YlC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXlG2YlC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XlG2YlC',
    'container.build_id' => 'c8b99bfa',
    'container.build_time' => 1566297824,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlG2YlC');
