<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOQ7xLka\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOQ7xLka/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOQ7xLka.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOQ7xLka\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOQ7xLka\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OQ7xLka',
    'container.build_id' => '7e64aab5',
    'container.build_time' => 1566385302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOQ7xLka');
